---
- name: Stop, start, or recycle Claims Demo integration APIs
  hosts: claims_demo_api:&windows
  gather_facts: true
  serial: "{{ deploy_parallelism | default('25%') }}"
  any_errors_fatal: true

  vars:
    iis_application_directory: "{{ claims_demo_api_deployment_path }}"
    iis_application_name: "{{ claims_demo_api_application_name }}"
    iis_application_pool_name: "{{ claims_demo_api_application_pool_name }}"
    iis_application_healthcheck_url: "{{ claims_demo_api_application_healthcheck_url }}"

  tasks:
    - name: Stop Claims Demo API
      ansible.builtin.import_role:
        name: common/stop_start_app_iis
        tasks_from: stop_app_iis.yml
      when:
        - stop_claims_demo_api is defined

    - name: Start Claims Demo API
      ansible.builtin.import_role:
        name: common/stop_start_app_iis
        tasks_from: start_app_iis.yml
      when:
        - start_claims_demo_api is defined

    - name: Recycle Claims Demo API
      ansible.builtin.import_role:
        name: common/stop_start_app_iis
        tasks_from: recycle_app_iis.yml
      when:
        - recycle_claims_demo_api is defined
