---
ansible_connection: winrm
ansible_port: 5986
ansible_winrm_scheme: https
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

edex_target_environment: "PreProd"
edex_backup_base_location: "C:\\ClaimsDemoBackup\\{{ '%Y%m%d' | ansible.builtin.strftime }}"
