---
- name: "Stop apppool for {{ iis_application_name | mandatory }}"
  ansible.windows.win_command:
    argv:
      - 'C:\Windows\System32\inetsrv\appcmd.exe'
      - stop
      - apppool
      - '/apppool.name:{{ iis_application_pool_name | mandatory }}'
  register: stop_apppool_result
  failed_when:
    - stop_apppool_result.rc != 0
    - stop_apppool_result.stdout is not ansible.builtin.regex('Application pool .* already stopped', ignorecase=True)
